// The Crowdfunding deck — the curriculum the learner walks through.
//
// Written to mirror the challenge README's checkpoints: explain a thing, then
// ask the learner to write one specific line, then test understanding. Small
// steps, no leaps, no assumed knowledge — this is an early challenge, so we don't
// assume they've seen mappings, events, or payable before.
//
// Voice: a senior dev walking a junior through what they're building. Lead with
// the situation, not the definition. No hype, no em dashes, no bold-label
// paragraphs. The concept prose is rewritten from the challenge's CONCEPTS.yaml,
// not lifted, because the source read a little flat.
import { CANONICAL, CROWDFUNDING_SKELETON } from "./crowdfunding-contracts";
import type { Card, Deck } from "./types";

const cards: Card[] = [
  {
    id: "trustless",
    type: "concept",
    tier1: "THE IDEA",
    tier2: "sutra",
    title: "Funding without a middleman",
    body: `Say a group of people want to pool money toward something. Normally someone has to sit in the middle holding the cash, an escrow service or a platform everyone agrees to trust. On Ethereum you can drop that middleman. You write the rules into a contract, deploy it, and the contract itself holds the money and enforces the rules.

Here's the thing you're building. People send ETH toward a goal. If enough comes in before a deadline, the money goes to whoever the campaign is funding. If not enough comes in, everyone can pull their money back out. Once it's deployed nobody can change those rules, not the contributors and not you. The worst case is everyone gets refunded.

That pattern is everywhere on Ethereum. People who have no reason to trust each other can still work together, because they're all trusting the same code instead of trusting a person. Crowdfunds, token launches, grants rounds, they're all the same idea wearing different clothes.`,
  },
  {
    id: "who-enforces",
    type: "think",
    tier1: "THINK",
    tier2: "prashna",
    title: "What if you turn greedy",
    question:
      "You wrote this contract and you're the one deploying it. A contributor worries that once their ETH is in, you'll quietly change the rules to send the whole pot to yourself. What can you honestly tell them about your own power over the contract after it's live?",
    rubricConcepts: [
      "even the creator has no special power once it's deployed",
      "there's no owner or admin key to change the rules",
      "the deployed code is fixed and can't be edited",
      "the only way you could cheat is a backdoor written before deploy",
      "they can read the code before contributing",
    ],
    hint: "Once it's deployed, what could you actually do to it? Do you have any access the contributors don't?",
  },
  {
    id: "shape",
    type: "code",
    tier1: "THE CODE",
    tier2: "darshan",
    title: "The shape of it",
    file: "CrowdFund.sol",
    fromAnchor: "constructor(address fundingRecipientAddress)",
    toAnchor: "fundingRecipient = fundingRecipientAddress;",
    note: `Here's the contract you'll fill in, a piece at a time. It's grouped into sections: errors and state variables near the top, then the constructor, then the functions, which are empty shells right now. The one thing already wired is \`fundingRecipient\` — the address that receives the money if the campaign succeeds. Everything else, you'll write.`,
  },
  {
    id: "tracking",
    type: "concept",
    tier1: "THE IDEA",
    tier2: "sutra",
    title: "Tracking who gave what",
    body: `The contract can't just remember the total that came in. It needs to know how much each person put in, individually. The reason is the refund case: if the campaign fails, everyone has to get back exactly what they contributed, no more and no less. You can't do that from a single total.

The tool for this in Solidity is a **mapping** — a key-value store, like a dictionary. Every key starts at zero by default, so nobody has to be set up ahead of time. The next card is where you'll work out exactly what to map to what.`,
  },
  {
    id: "balances",
    type: "your-turn",
    tier1: "YOUR TURN",
    tier2: "lekhana",
    title: "Track the balances",
    file: "CrowdFund.sol",
    slot: "__BALANCES__",
    prompt: `A mapping points one thing at another. You may have seen \`mapping(uint256 => address) public tokenOwner\` in an NFT: give it a token id and it hands back the owner, so \`tokenOwner[1]\` is the address that owns token #1. The key is the id, the value is the address.

Now your turn. You need the opposite shape. For any contributor's \`address\`, you want to look up the total ETH they've put in. So what's the key, and what's the value? Write the state variable, make it \`public\` so the frontend can read it, and name it \`balances\`.`,
    placeholder: "mapping(/* key? */ => /* value? */) public balances;",
    canonical: CANONICAL.__BALANCES__,
    explain: {
      prompt: `One line: why is the contributor's \`address\` the key and the amount the value, and not the other way around?`,
      rubricConcepts: [
        "you look things up by the contributor's address",
        "the address is who, the amount is what they gave",
        "you need to find a given person's balance",
        "key is what you search by",
        "address points to their amount",
      ],
    },
  },
  {
    id: "balances-added",
    type: "code",
    tier1: "THE CODE",
    tier2: "darshan",
    title: "It's in the contract now",
    file: "CrowdFund.sol",
    fromAnchor: "public balances",
    note: `That's your \`balances\` mapping sitting with the rest of the state. Every address reads as zero until they contribute, and you'll add to it each time someone does.`,
  },
  {
    id: "payable-idea",
    type: "concept",
    tier1: "THE IDEA",
    tier2: "sutra",
    title: "Taking the money in",
    body: `For a function to actually receive ETH, you have to mark it \`payable\`. Without that keyword, the contract rejects any ETH sent to it. The \`contribute()\` function is already marked payable, so it's ready to accept money.

Inside any function you also get two things straight from the transaction itself. \`msg.sender\` is the address that called the function, and \`msg.value\` is how much ETH they attached. Neither can be faked, they come from the signed transaction. So recording a contribution is really just: take \`msg.value\` and add it to \`msg.sender\`'s entry in the mapping.`,
  },
  {
    id: "contribute",
    type: "your-turn",
    tier1: "YOUR TURN",
    tier2: "lekhana",
    title: "Write contribute()",
    file: "CrowdFund.sol",
    slot: "__CONTRIBUTE__",
    prompt: `One line. Add the sender's \`msg.value\` to their balance in the mapping. Remember to add, not overwrite, so repeat contributions stack instead of erasing the earlier ones.`,
    placeholder: "balances[msg.sender] += /* the amount they sent */;",
    canonical: CANONICAL.__CONTRIBUTE__,
    explain: {
      prompt: `Why \`+=\` and not just \`=\` here?`,
      rubricConcepts: [
        "= would overwrite their earlier contribution",
        "+= adds to what's already there",
        "someone can contribute more than once",
        "their previous amount has to survive",
        "you accumulate, not replace",
      ],
    },
  },
  {
    id: "contribute-added",
    type: "code",
    tier1: "THE CODE",
    tier2: "darshan",
    title: "There's contribute()",
    file: "CrowdFund.sol",
    fromAnchor: "balances[msg.sender] += msg.value",
    note: `One line, and \`contribute()\` does its whole job: take whatever ETH came in and add it to the sender's running total.`,
  },
  {
    id: "try-contribute",
    type: "try-it",
    tier1: "TRY IT",
    tier2: "prayoga",
    title: "Put some ETH in",
    scenario: "contribute",
    body: `Your contract is live. Send it some ETH and watch your tracked balance and the contract's balance both climb, running against the \`contribute()\` you just wrote. (Anything you haven't written yet, we fill in for you so the contract runs.)`,
  },
  {
    id: "sending-eth",
    type: "concept",
    tier1: "THE IDEA",
    tier2: "sutra",
    title: "Sending ETH is where it gets scary",
    body: `When the campaign fails, people need their money back. Sounds easy: just send each person their ETH. But sending ETH is one of the most dangerous things you can do in Solidity, and getting the order of operations wrong can drain the whole contract.

The danger is called a **reentrancy attack**. When you send ETH to an address, if that address is itself a contract, it gets to run code the moment it receives the money. That code can call straight back into your withdraw function before you've updated anyone's balance. So it withdraws, re-enters, withdraws again, re-enters again, draining everything before the first call ever finishes. This is exactly how the famous DAO hack played out in 2016.

The fix is an ordering rule, sometimes called Checks, Effects, Interactions. First check that the withdrawal is allowed. Then update your own state, set the person's balance to zero. Only then send the ETH. If a malicious contract tries to re-enter, the balance is already zero, so there's nothing left to take. The whole trick is doing the state change before the external call, never after.`,
  },
  {
    id: "zero-first",
    type: "think",
    tier1: "THINK",
    tier2: "prashna",
    title: "Why empty the balance first",
    question:
      "Why does it matter so much that you set someone's balance to zero before you send them their ETH, instead of after? What goes wrong if you flip those two lines?",
    rubricConcepts: [
      "the address you pay can be a contract that runs code on receipt",
      "it calls back into withdraw before your state has updated",
      "if the balance isn't zero yet it can withdraw again and again",
      "zeroing first means there's nothing left to re-take",
      "this is reentrancy, the same shape as the DAO hack",
    ],
    hint: "Picture the person you're paying being a contract that runs code the instant it gets ETH, and that code calls withdraw again.",
  },
  {
    id: "open-to-withdraw",
    type: "your-turn",
    tier1: "YOUR TURN",
    tier2: "lekhana",
    title: "Open the door to refunds",
    file: "CrowdFund.sol",
    slot: "__OPEN_TO_WITHDRAW__",
    prompt: `Refunds shouldn't be allowed while the campaign is still running, only once it's failed. Add a \`public\` boolean called \`openToWithdraw\` to track that. It defaults to \`false\`, which is what you want.`,
    placeholder: "bool public /* name the flag */;",
    canonical: CANONICAL.__OPEN_TO_WITHDRAW__,
    explain: {
      prompt: `Why does this flag start out \`false\` instead of \`true\`?`,
      rubricConcepts: [
        "refunds must be closed while the campaign is still running",
        "withdrawals should only open once it fails",
        "false is the safe default",
        "you don't want people pulling out mid-campaign",
        "execute is what flips it to true on failure",
      ],
    },
  },
  {
    id: "open-to-withdraw-added",
    type: "code",
    tier1: "THE CODE",
    tier2: "darshan",
    title: "The refund switch",
    file: "CrowdFund.sol",
    fromAnchor: "bool public openToWithdraw",
    note: `\`openToWithdraw\` sits with the rest of the state, starting at \`false\`. Nothing flips it except your own code, once the campaign has failed.`,
  },
  {
    id: "withdraw",
    type: "your-turn",
    tier1: "YOUR TURN",
    tier2: "lekhana",
    title: "Write withdraw()",
    file: "CrowdFund.sol",
    slot: "__WITHDRAW__",
    prompt: `Follow the ordering rule. First, if \`openToWithdraw\` is false, revert with \`NotOpenToWithdraw\`. Then read the caller's balance into a local variable and set their stored balance to zero. Only then send them the ETH with \`msg.sender.call{value: ...}("")\`, and revert with \`TransferFailed\` if it didn't succeed. (The errors are already declared up top.)`,
    placeholder:
      "if (!openToWithdraw) revert NotOpenToWithdraw();\n\nuint256 balance = balances[msg.sender];\n// zero it out, then send, then check success",
    canonical: CANONICAL.__WITHDRAW__,
    explain: {
      prompt: `Why read the balance into a local variable before you zero the stored one?`,
      rubricConcepts: [
        "you still need the amount to actually send after zeroing storage",
        "if you zeroed first without saving it you'd send nothing",
        "keep the value in memory, clear the record on chain",
        "the local copy survives the state change",
      ],
    },
  },
  {
    id: "withdraw-added",
    type: "code",
    tier1: "THE CODE",
    tier2: "darshan",
    title: "Refunds, in order",
    file: "CrowdFund.sol",
    fromAnchor: "function withdraw()",
    toAnchor: "revert TransferFailed(msg.sender, balance);",
    note: `Check, then effect, then interaction: confirm withdrawals are open, zero the balance, and only then send. By the time the ETH leaves, there's nothing left for a re-entering contract to claim.`,
  },
  {
    id: "state-machine",
    type: "concept",
    tier1: "THE IDEA",
    tier2: "sutra",
    title: "A contract is a state machine",
    body: `It helps to think of your contract as moving through a few distinct states. First there's the funding period, where contributions are open and the clock is ticking. Then it lands in one of two end states: success, where enough ETH came in and it gets forwarded to the recipient, or failure, where it didn't and everyone can withdraw.

There's a catch that trips up everyone new to smart contracts: a contract can't do anything on its own. There's no timer, no scheduler, nothing that fires when the deadline passes. The contract just sits there. Even after the deadline, it stays in the funding state until somebody sends a transaction that tells it to check the clock and move on. So you need an \`execute()\` function that anyone can call once the deadline is up, to push the contract into success or failure.`,
  },
  {
    id: "deadline-threshold",
    type: "your-turn",
    tier1: "YOUR TURN",
    tier2: "lekhana",
    title: "Set the deadline and the goal",
    file: "CrowdFund.sol",
    slot: "__DEADLINE_THRESHOLD__",
    prompt: `Add two state variables. A \`deadline\`, set to the current time (\`block.timestamp\`) plus 30 seconds. And a \`threshold\` constant set to \`1 ether\`, the amount you need to raise for the campaign to count as a success.`,
    placeholder:
      "uint256 public deadline = block.timestamp + /* how long? */;\nuint256 public constant threshold = /* the goal */;",
    canonical: CANONICAL.__DEADLINE_THRESHOLD__,
    explain: {
      prompt: `Why can \`threshold\` be a \`constant\` but \`deadline\` can't?`,
      rubricConcepts: [
        "threshold is a fixed value known ahead of time",
        "deadline depends on block.timestamp at deploy",
        "a constant is baked in when the code compiles",
        "deadline is computed at construction, not compile time",
        "you can't make a runtime value constant",
      ],
    },
  },
  {
    id: "deadline-threshold-added",
    type: "code",
    tier1: "THE CODE",
    tier2: "darshan",
    title: "The clock and the goal",
    file: "CrowdFund.sol",
    fromAnchor: "uint256 public deadline",
    toAnchor: "uint256 public constant threshold",
    note: `The \`deadline\` is locked in the moment the contract deploys, and \`threshold\` is the line the campaign has to clear to count as a win.`,
  },
  {
    id: "execute",
    type: "your-turn",
    tier1: "YOUR TURN",
    tier2: "lekhana",
    title: "Write execute()",
    file: "CrowdFund.sol",
    slot: "__EXECUTE__",
    prompt: `First, if the deadline hasn't passed yet (\`block.timestamp <= deadline\`), revert with \`TooEarly\`. Then check the result: if the contract's balance reached the \`threshold\`, mark the campaign \`completed\` and forward the whole balance to \`fundingRecipient\` with \`fundingRecipient.call{value: address(this).balance}("")\` (revert with \`TransferFailed\` if the send fails). Otherwise, set \`openToWithdraw\` to true so contributors can get refunds.`,
    placeholder:
      "if (block.timestamp <= deadline) revert TooEarly(deadline, block.timestamp);\n\n// if the threshold was met, forward the funds; otherwise open withdrawals",
    canonical: CANONICAL.__EXECUTE__,
    explain: {
      prompt: `Why check the deadline and revert first, before doing anything else?`,
      rubricConcepts: [
        "the campaign can't settle before it's over",
        "no one should be able to execute early",
        "guard first, decide the outcome second",
        "you only know success or failure once time is up",
        "checks come before effects",
      ],
    },
  },
  {
    id: "execute-added",
    type: "code",
    tier1: "THE CODE",
    tier2: "darshan",
    title: "The two endings",
    file: "CrowdFund.sol",
    fromAnchor: "function execute()",
    toAnchor: "openToWithdraw = true;",
    note: `One function, both outcomes. If the goal was met it marks the campaign done and forwards the pot; if not, it opens the door to refunds.`,
  },
  {
    id: "timeleft",
    type: "your-turn",
    tier1: "YOUR TURN",
    tier2: "lekhana",
    title: "Show the time left",
    file: "CrowdFund.sol",
    slot: "__TIMELEFT__",
    prompt: `The frontend wants to show a countdown, so finish \`timeLeft()\`. If the \`deadline\` is still in the future, return how many seconds are left. Otherwise return 0. A ternary does it in one line.`,
    placeholder: "return deadline > block.timestamp ? /* seconds remaining */ : 0;",
    canonical: CANONICAL.__TIMELEFT__,
    explain: {
      prompt: `Why return 0 once the deadline has passed, instead of letting the subtraction run?`,
      rubricConcepts: [
        "a uint can't go negative",
        "deadline minus a later timestamp would underflow and revert",
        "no time left should just read as zero",
        "you can't represent negative seconds in a uint",
        "the ternary guards against the underflow",
      ],
    },
  },
  {
    id: "timeleft-added",
    type: "code",
    tier1: "THE CODE",
    tier2: "darshan",
    title: "The countdown",
    file: "CrowdFund.sol",
    fromAnchor: "return deadline > block.timestamp",
    note: `\`timeLeft()\` hands the frontend a clean number: seconds remaining while the campaign runs, and a flat zero once the deadline is behind it.`,
  },
  {
    id: "must-poke",
    type: "think",
    tier1: "THINK",
    tier2: "prashna",
    title: "Why someone has to poke it",
    question:
      "The deadline passes and the campaign didn't reach its goal. Why can't contributors just withdraw right then? Why does someone have to call execute() first?",
    rubricConcepts: [
      "a contract can't run code on its own",
      "nothing happens until a transaction triggers it",
      "execute is what flips the state and opens withdrawals",
      "the deadline passing doesn't change any state by itself",
      "someone has to send the transaction that moves it on",
    ],
    hint: "Remember that a contract can't run code on its own. Nothing happens until a transaction makes it happen.",
  },
  {
    id: "try-fail",
    type: "try-it",
    tier1: "TRY IT",
    tier2: "prayoga",
    title: "Let the campaign fail",
    scenario: "failure-refund",
    body: `Contribute less than the 1 ETH threshold, then let the deadline pass and call \`execute()\`. Since the goal wasn't met, it opens withdrawals, and you can pull your money back. Try calling execute() before the deadline and you'll see it refuse.`,
  },
  {
    id: "try-succeed",
    type: "try-it",
    tier1: "TRY IT",
    tier2: "prayoga",
    title: "Let it succeed",
    scenario: "success-forward",
    body: `Now the other ending. Contribute more than the threshold, let the deadline pass, and call \`execute()\`. This time the money forwards to the recipient address and the contract's \`completed\` flag flips to true. Same function, two outcomes, decided entirely by how much came in.`,
  },
  {
    id: "receive-idea",
    type: "concept",
    tier1: "THE IDEA",
    tier2: "sutra",
    title: "Catching loose ETH",
    body: `Right now someone can only contribute by calling \`contribute()\` directly. But people (and wallets) sometimes just send ETH straight to a contract address with no function specified. By default that money would be rejected.

Solidity has a special function for this called \`receive()\`. It runs automatically whenever the contract gets ETH with no function named. You can use it to catch that ETH and route it into your normal contribution logic, so a plain transfer counts as a contribution too. Better experience, and no money left stranded.`,
  },
  {
    id: "receive",
    type: "your-turn",
    tier1: "YOUR TURN",
    tier2: "lekhana",
    title: "Write receive()",
    file: "CrowdFund.sol",
    slot: "__RECEIVE__",
    prompt: `One line. When ETH arrives with no function specified, just call \`contribute()\` so it gets tracked like any other contribution.`,
    placeholder: "// route a plain transfer into a contribution",
    canonical: CANONICAL.__RECEIVE__,
    explain: {
      prompt: `Why route a plain transfer through \`contribute()\` instead of just letting the contract hold the ETH?`,
      rubricConcepts: [
        "otherwise that ETH is untracked",
        "it wouldn't count toward their balance",
        "there'd be no refund record for it",
        "contribute does the bookkeeping",
        "a plain transfer would otherwise be stranded",
      ],
    },
  },
  {
    id: "receive-added",
    type: "code",
    tier1: "THE CODE",
    tier2: "darshan",
    title: "No stranded ETH",
    file: "CrowdFund.sol",
    fromAnchor: "receive() external payable",
    toAnchor: "contribute();",
    note: `Now a plain transfer to the contract lands in \`contribute()\` like any other, so it gets tracked and stays refundable.`,
  },
  {
    id: "edge-cases",
    type: "concept",
    tier1: "THE IDEA",
    tier2: "sutra",
    title: "Closing the trapdoors",
    body: `Once the happy path works, the real smart-contract thinking starts: what could go wrong? This is where it differs from normal programming. A bug in a web app you can patch tomorrow. A contract is deployed once and can't be changed, so a hole stays open forever.

Here's a concrete one. What if someone sends ETH after the campaign already succeeded and the money was forwarded? That ETH lands in a contract that's done. There's no path to move it out anymore, so it's stuck for good. The way you handle this is with a guard. A **modifier** is a reusable check you attach to a function, and it runs before the function body. You can write one that refuses to run once the campaign is already completed, and attach it to the functions that shouldn't fire after the campaign is over. The goal is to make the bad state impossible to reach, not just unlikely.`,
  },
  {
    id: "too-late",
    type: "think",
    tier1: "THINK",
    tier2: "prashna",
    title: "Money sent too late",
    question:
      "Someone sends ETH to the contract after the campaign already succeeded and the funds were forwarded. What happens to that ETH, and why is there no way to get it back out?",
    rubricConcepts: [
      "the ETH is trapped in the contract",
      "execute already ran and the completed guard stops it running again",
      "withdraw only refunds tracked contributions, not this stray ETH",
      "no function left can move that ETH out",
      "it's stuck permanently",
    ],
    hint: "Walk through every function that moves ETH out of the contract, and ask whether any of them still works once the campaign is done.",
  },
  {
    id: "modifier",
    type: "your-turn",
    tier1: "YOUR TURN",
    tier2: "lekhana",
    title: "Guard against double-funding",
    file: "CrowdFund.sol",
    slot: "__MODIFIER__",
    prompt: `Fill in the \`notCompleted\` modifier's guard. If the campaign is already \`completed\`, revert with \`AlreadyCompleted\`. It's already attached to contribute, withdraw, and execute, so once you write this one line, those functions are all protected.`,
    placeholder: "// revert if the campaign is already completed",
    canonical: CANONICAL.__MODIFIER__,
    explain: {
      prompt: `Why write this as a modifier instead of pasting the same check into each function?`,
      rubricConcepts: [
        "one place to write it and one place to change it",
        "it's reused across contribute, withdraw, and execute",
        "less chance of forgetting it on one function",
        "keeps the guard consistent everywhere",
        "avoids repeating yourself",
      ],
    },
  },
  {
    id: "modifier-added",
    type: "code",
    tier1: "THE CODE",
    tier2: "darshan",
    title: "One guard, three doors",
    file: "CrowdFund.sol",
    fromAnchor: "modifier notCompleted()",
    toAnchor: "if (completed) revert AlreadyCompleted();",
    note: `That one line now guards \`contribute\`, \`withdraw\`, and \`execute\` at once. Once the campaign is completed, none of them will run.`,
  },
  {
    id: "ship-it",
    type: "ship-it",
    tier1: "SHIP IT",
    tier2: "prakashana",
    title: "Deploy it for real",
    body: `You wrote all of it: tracking contributions, refunding safely, the deadline, the two endings, and the guard. Deploy the \`CrowdFund\` contract to the in-browser chain and watch the whole thing come up live.`,
  },
  {
    id: "what-you-built",
    type: "recap",
    tier1: "WHAT YOU BUILT",
    tier2: "samhita",
    title: "What you built",
    body: `This is the contract you co-authored, line by line. A group of strangers can now pool money toward a goal with nobody in the middle, get refunded safely if it falls short, and forward the funds automatically if it succeeds. The patterns underneath it, on-chain tracking, the order-of-operations rule for moving ETH, and modeling a contract as a state machine, are the same ones running under most of Ethereum.`,
  },
];

export const CROWDFUNDING_DECK: Deck = {
  id: "crowdfunding",
  title: "Crowdfunding",
  challenge: "speedrunethereum · crowdfunding",
  skeleton: CROWDFUNDING_SKELETON,
  cards,
};
